version: '3.8'

services:
  web:
    container_name: portfolio-website
    restart: unless-stopped
    build: .
    command: npm start
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
