version: '3.8'

services:
  dev:
    container_name: portfolio-website
    build: .
    command: npm start
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
