version: '3.8'

services:
  web:
    container_name: portfolio-website
    command: serve -s dist
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
