# Use an official Node.js runtime as the base image
FROM node:18-alpine

COPY public/ /react-docker-example/public
COPY src/ /react-docker-example/src
COPY package.json /react-docker-example/

RUN npm install

CMD ["npm", "start"]
