services:
  web:
    container_name: portfolio-website
    restart: unless-stopped
    build: .
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: serve -s build -l 3000
