version: '3.8'

services:
  web:
    container_name: portfolio-website
    restart: unless-stopped
    build: .
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
