version: '3.8'

services:
  dev:
    container_name: portfolio-website-dev
    build:
      context: .
      target: builder # Use the builder stage for development
    command: npm start
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development

  prod:
    container_name: portfolio-website-prod
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
