name: run-docker-compose
on:
  push:
    branches:
      - main 
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Create env file
        run: |
          touch ./portfolio-website/.env
          echo "REACT_APP_DIALOGFLOW_PROJECT_ID=${{ secrets.REACT_APP_DIALOGFLOW_PROJECT_ID }}" >> ./portfolio-website/.env
          echo "REACT_APP_DIALOGFLOW_AGENT_ID=${{ secrets.REACT_APP_DIALOGFLOW_AGENT_ID }}" >> ./portfolio-website/.env
          
      - name: Run Docker Compose
        run: docker compose -f ./portfolio-website/docker-compose.yml up -d --force-recreate --build
